routing:
    showHome:
        path: /
        module: Home\Home
        action: isCalled
        name: Home\Home|isCalled
        method: GET

    showPostsList:
        path: /posts
        module: Blog\Post\Post
        action: showList
        name: Blog\Post\Post|showList
        method: GET

    showPostWithId:
        path: /post/:id
        module: Blog\Post\Post
        action: showSingle
        name: Blog\Post\Post|showSingle
        method: GET

    showPostWithSlugAndId:
        path: /post/:slug-:id
        module: Blog\Post\Post
        action: showSingle
        name: Blog\Post\Post|showSingle
        method: GET

    showPostsWithPaging:
        path: /posts/page/:pageId
        module: Blog\Post\Post
        action: showListWithPaging
        name: Blog\Post\Post|showListWithPaging
        method: GET

    showPostComment:
        path: /comment-post/:id
        module: Blog\Post\Post
        action: showSingle
        name: Blog\Post\Post|showSingle
        method: GET

    showAdminHome:
        path: /admin
        module: Admin\Home\AdminHome
        action: showAdminHome
        name: Admin\Home\AdminHome|showAdminHome
        method: GET

    showAdminAccess:
        path: /admin/login
        module: Admin\User\AdminUser
        action: showAdminAccess
        name: Admin\User\AdminUser|showAdminAccess
        method: GET

    showAdminRegister:
        path: /admin/register
        module: Admin\User\AdminUser
        action: showAdminRegister
        name: Admin\User\AdminUser|showAdminRegister
        method: GET

    showAdminRequestNewPassword:
        path: /admin/request-new-password
        module: Admin\User\AdminUser
        action: showAdminRequestNewPassword
        name: Admin\User\AdminUser|showAdminRequestNewPassword
        method: GET

    showAdminRenewPassword:
        path: /admin/renew-password
        module: Admin\User\AdminUser
        action: showAdminRenewPassword
        name: Admin\User\AdminUser|showAdminRenewPassword
        method: GET

    showAdminDisconnect:
        path: /admin/logout
        module: Admin\User\AdminUser
        action: logoutUser
        name: Admin\User\AdminUser|logoutUser
        method: GET

    showAdminPosts:
        path: /admin/posts
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminHomeDeleteContact:
        path: /admin/delete-contact/:id
        module: Admin\Home\AdminHome
        action: showAdminHome
        name: Admin\Home\AdminHome|showAdminHome
        method: GET

    showAdminHomeDeleteUser:
        path: /admin/delete-user/:id
        module: Admin\Home\AdminHome
        action: showAdminHome
        name: Admin\Home\AdminHome|showAdminHome
        method: GET

    showAdminPostsDeleteComment:
        path: /admin/delete-comment/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsValidateComment:
        path: /admin/validate-comment/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsPublishComment:
        path: /admin/publish-comment/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsUnpublishComment:
        path: /admin/unpublish-comment/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminCreatePost:
        path: /admin/add-post
        module: Admin\Post\AdminPost
        action: addPost
        name: Admin\Post\AdminPost|addPost
        method: GET

    showAdminUpdatePost:
        path: /admin/update-post/:id
        module: Admin\Post\AdminPost
        action: updatePost
        name: Admin\Post\AdminPost|updatePost
        method: GET

    showAdminDeletePost:
        path: /admin/delete-post/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsValidatePost:
        path: /admin/validate-post/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsPublishPost:
        path: /admin/publish-post/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    showAdminPostsUnpublishPost:
        path: /admin/unpublish-post/:id
        module: Admin\Post\AdminPost
        action: showAdminPosts
        name: Admin\Post\AdminPost|showAdminPosts
        method: GET

    home:
        path: /
        module: Home\Home
        action: isCalled
        name: Home\Home|isCalled
        method: POST

    postComment:
        path: /comment-post/:id
        module: Blog\Post\Post
        action: commentPost
        name: Blog\Post\Post|commentPost
        method: POST

    adminRegister:
        path: /admin/register
        module: Admin\User\AdminUser
        action: registerUser
        name: Admin\User\AdminUser|registerUser
        method: POST

    adminConnect:
        path: /admin/login
        module: Admin\User\AdminUser
        action: loginUser
        name: Admin\User\AdminUser|loginUser
        method: POST

    adminRequestNewPassword:
        path: /admin/request-new-password
        module: Admin\User\AdminUser
        action: requestNewPassword
        name: Admin\User\AdminUser|requestNewPassword
        method: POST

    adminRenewPassword:
        path: /admin/renew-password
        module: Admin\User\AdminUser
        action: renewPassword
        name: Admin\User\AdminUser|renewPassword
        method: POST

    adminHomeDeleteContact:
        path: /admin/delete-contact/:id
        module: Admin\Home\AdminHome
        action: deleteContact
        name: Admin\Home\AdminHome|deleteContact
        method: POST

    adminHomeDeleteUser:
        path: /admin/delete-user/:id
        module: Admin\Home\AdminHome
        action: deleteUser
        name: Admin\Home\AdminHome|deleteUser
        method: POST

    adminPostsDeleteComment:
        path: /admin/delete-comment/:id
        module: Admin\Post\AdminPost
        action: deleteComment
        name: Admin\Post\AdminPost|deleteComment
        method: POST

    adminPostsValidateComment:
        path: /admin/validate-comment/:id
        module: Admin\Post\AdminPost
        action: validateComment
        name: Admin\Post\AdminPost|validateComment
        method: POST

    adminPostsPublishComment:
        path: /admin/publish-comment/:id
        module: Admin\Post\AdminPost
        action: publishComment
        name: Admin\Post\AdminPost|publishComment
        method: POST

    adminPostsUnpublishComment:
        path: /admin/unpublish-comment/:id
        module: Admin\Post\AdminPost
        action: unpublishComment
        name: Admin\Post\AdminPost|unpublishComment
        method: POST

    adminPostsCreatePost:
        path: /admin/add-post
        module: Admin\Post\AdminPost
        action: addPost
        name: Admin\Post\AdminPost|addPost
        method: POST

    adminPostsUpdatePost:
        path: /admin/update-post/:id
        module: Admin\Post\AdminPost
        action: updatePost
        name: Admin\Post\AdminPost|updatePost
        method: POST

    adminPostsDeletePost:
        path: /admin/delete-post/:id
        module: Admin\Post\AdminPost
        action: deletePost
        name: Admin\Post\AdminPost|deletePost
        method: POST

    adminPostsValidatePost:
        path: /admin/validate-post/:id
        module: Admin\Post\AdminPost
        action: validatePost
        name: Admin\Post\AdminPost|validatePost
        method: POST

    adminPostsPublishPost:
        path: /admin/publish-post/:id
        module: Admin\Post\AdminPost
        action: publishPost
        name: Admin\Post\AdminPost|publishPost
        method: POST

    adminPostsUnpublishPost:
        path: /admin/unpublish-post/:id
        module: Admin\Post\AdminPost
        action: unpublishPost
        name: Admin\Post\AdminPost|unpublishPost
        method: POST