config:
    domain: https://www.example.com (or local virtual host)
    websiteName: your website name
    https: true or false (your type of protocol)
    appDebug: true or false (show debug details for exceptions)
    home:
        profileTitleDesc: profile title description
        profileIntro: profile intro
        profileImage: profile image name
        profileImageDesc: profile image description
        profileImageLabel: profile image label
        onlineCVResume: online CV resume absolute url
        pdfCVResume: pdf file cv resume name
    footer:
        socialLinks:
            linkedInProfile: profile absolute url
            githubProfile: profile absolute url
            stackoverflowProfile: profile absolute url
            viadeoProfile: profile absolute url
    database:
        dbHost: your_db_host (local or remote server address)
        dbName: your_db_name
        dbUser: your_db_user_name
        dbPwd: your_db_pwd
    posts:
        postPerPage: 5 (number - post quantity to show per page for posts list)
    singlePost:
        commentPerSlide: 5 (number - comment quantity to show per slide item for single post)
    admin:
        home:
            contactPerSlide: 5 (number - contact quantity to show per slide item)
            userPerSlide: 5 (number - user quantity to show per slide item)
        posts:
            postPerSlide: 5 (number - post quantity to show per slide item)
            commentPerSlide: 5 (number - comment quantity to show per slide item)
    googleRecaptcha:
        siteKey: your_site_key
        secretKey: your_secret_key
    contactForm:
        ajaxMode: true or false
        contactEmail: your_email_address_to_receive_a_message
    # example: https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phpsPHPMailer:
    # https://security.google.com/settings/security/activity?hl=en&pli=1
    # https://myaccount.google.com/lesssecureapps
    # https://accounts.google.com/DisplayUnlockCaptcha
    # https://stackoverflow.com/questions/21937586/phpmailer-smtp-error-password-command-failed-when-send-mail-from-my-server
    contactPHPMailer:
        enableExceptions: true or false
        SMTPDebug: 0 (or 1, 2, 3, 4)
        SMTPAuth: true or false
        port: 587 (number - 587 for tls or 465 for ssl)
        host: your_smtp_host_name (for instance smtp.gmail.com)
        SMTPSecure: tls or ssl
        SMTPUserName: your_mail_for_stmp_authentication (SMTPAuth set to true)
        SMTPPwd: your_password_for_stmp_authentication (SMTPAuth set to true)
    mailing:
        hostedImagesAbsoluteURL: absolute url to load images in html emails in general (https://www.example.com/assets/images/)