config:
    domain: www.example.com
    appDebug: true or false (show debug details for exceptions)
    database:
        dbHost: localhost
        dbName: phpblog
        dbUser: root
        dbPwd:
    posts:
        postPerPage: 5 (number - post quantity per page for posts list)
    googleRecaptcha:
        siteKey: your_site_key
        secretKey: your_secret_key
    contactForm:
        ajaxMode: true or false
        contactEmail: your_email_address_to_receive_a_message
    # example: https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phpsPHPMailer:    
    contactPHPMailer: 
        EnableExceptions: true or false
        SMTPDebug: 0 (or 1, 2, 3, 4)
        SMTPAuth: true or false
        Port: 587 (number - 587 for tls or 465 for ssl)
        Host: your_smtp_host_name (for instance smtp.gmail.com)
        SMTPSecure: tls or ssl
        SMTPUserName: your_mail_for_stmp_authentication (SMTPAuth set to true)
        SMTPPwd: your_password_for_stmp_authentication (SMTPAuth set to true)
        HostedImagesAbsoluteURL: absolute url to load images in html message (https://www.example.com/assets/images/)