service:
  formValidator:
    -
      name: home.contactForm
      formIdentifier: cf_
      formDatasRequest: POST
  mailer:
    - 
      name: home.contactForm
      type: PHPMailer
      use: contactForm
      sendingMethod: smtp
  captcha:
    - 
      name: home.contactForm
      type: ReCaptcha


